import re
from pathlib import Path
from dataclasses import dataclass

_SUPPORTED_PLATFORMS: dict[str, str]
_BASE_NAME_PATTERN: re.Pattern[str]

@dataclass(frozen=True)
class ProjectEnvironment:
    activate_command: str
    deactivate_command: str
    create_command: str
    create_from_yaml_command: str | None
    remove_command: str
    install_dependencies_command: str
    update_command: str | None
    export_yaml_command: str
    export_spec_command: str
    install_project_command: str
    uninstall_project_command: str
    environment_name: str
    environment_directory: Path
    @classmethod
    def resolve_project_environment(
        cls,
        project_root: Path,
        environment_name: str,
        python_version: str = "3.13",
        environment_directory: Path | None = None,
        *,
        prerelease: bool = False,
    ) -> ProjectEnvironment: ...
    def environment_exists(self) -> bool: ...

def format_message(message: str) -> str: ...
def colorize_message(message: str, color: str, *, wrap: bool = True) -> str: ...
def resolve_project_directory() -> Path: ...
def resolve_library_root(project_root: Path) -> Path: ...
def generate_typed_marker(library_root: Path) -> None: ...
def move_stubs(stubs_directory: Path, library_root: Path) -> None: ...
def delete_stubs(library_root: Path) -> None: ...
def verify_pypirc(file_path: Path) -> bool: ...
def _get_copy_number(path: Path, copy_pattern: re.Pattern[str]) -> int: ...
def _get_base_name(dependency: str) -> str: ...
def _add_dependency(dependency: str, dependencies: list[str], processed_dependencies: set[str]) -> None: ...
def _resolve_dependencies(project_root: Path) -> tuple[str, ...]: ...
def _resolve_project_name(project_root: Path) -> str: ...
def _resolve_mamba_environments_directory() -> Path: ...
def _resolve_environment_files(project_root: Path, environment_base_name: str) -> tuple[str, Path, Path]: ...
def _check_package_engines() -> None: ...
