import re
from types import TracebackType
from pathlib import Path
from dataclasses import dataclass
from collections.abc import Callable as Callable

_SUPPORTED_PLATFORMS: dict[str, str]
_BASE_NAME_PATTERN: re.Pattern[str]
_FILE_RETRY_COUNT: int
_FILE_RETRY_INITIAL_DELAY: float
_NETLIFY_API_URL: str
_NETLIFY_DEPLOY_TIMEOUT: int
_APPLICATION_NAME: str
_APPLICATION_AUTHOR: str
_PYPIRC_FILE_NAME: str
_NETLIFYRC_FILE_NAME: str
_NETLIFY_SITE_FILE_NAME: str
_NETLIFY_SITE_SUFFIX: str
_PYTHON_PROJECT_ITEMS: tuple[str, ...]
_DOCUMENTED_PROJECT_ITEMS: tuple[str, ...]
_CERTIFICATE_VARIABLES: dict[str, str | None]

@dataclass(frozen=True, slots=True)
class ProjectEnvironment:
    activate_command: str
    deactivate_command: str
    create_command: str
    create_dry_run_command: str
    create_from_yaml_command: str | None
    remove_command: str
    install_dependencies_command: str
    update_command: str | None
    install_project_command: str
    uninstall_project_command: str
    environment_name: str
    environment_directory: Path
    environment_yaml_path: Path
    @classmethod
    def resolve_project_environment(
        cls,
        project_root: Path,
        environment_name: str,
        python_version: str = "3.13",
        environment_directory: Path | None = None,
        *,
        prerelease: bool = False,
    ) -> ProjectEnvironment: ...
    def verify_removable(self) -> None: ...
    def environment_exists(self) -> bool: ...
    def export_environment(self) -> None: ...

@dataclass(frozen=True, slots=True)
class NetlifyMigrationResult:
    token_migrated: bool
    site_migrated: bool
    def __bool__(self) -> bool: ...

def format_message(message: str) -> str: ...
def colorize_message(message: str, color: str, *, wrap: bool = True) -> str: ...
def resolve_project_directory() -> Path: ...
def resolve_documented_project_directory() -> Path: ...
def resolve_library_root(project_root: Path) -> Path: ...
def generate_typed_marker(library_root: Path) -> None: ...
def move_stubs(stubs_directory: Path, library_root: Path) -> None: ...
def delete_stubs(library_root: Path) -> None: ...
def resolve_application_directory() -> Path: ...
def resolve_pypirc_path() -> Path: ...
def resolve_netlifyrc_path() -> Path: ...
def verify_pypirc(file_path: Path) -> bool: ...
def verify_netlifyrc(file_path: Path) -> bool: ...
def derive_netlify_site(project_root: Path) -> str: ...
def read_netlify_site(project_root: Path) -> str | None: ...
def write_netlify_site(project_root: Path, site: str) -> None: ...
def migrate_legacy_pypirc(project_root: Path) -> bool: ...
def migrate_legacy_netlifyrc(project_root: Path) -> NetlifyMigrationResult: ...
def deploy_documentation(documentation_directory: Path, site: str, token: str) -> str: ...
def robust_rmtree(path: Path) -> None: ...
def repair_stale_certificate_variables() -> tuple[str, ...]: ...
def _quote_path(path: Path) -> str: ...
def _declares_dependencies(specification_lines: list[str]) -> bool: ...
def _resolve_project_directory(
    required_items: tuple[str, ...], project_description: str, items_description: str
) -> Path: ...
def _rmtree_onerror(
    failing_function: Callable[[str], None],
    path: str,
    exception_information: tuple[type[BaseException], BaseException, TracebackType],
) -> None: ...
def _unlink_with_retry(path: Path, *, missing_ok: bool = False) -> None: ...
def _rename_with_retry(source: Path, destination: Path) -> None: ...
def _get_copy_number(path: Path, copy_pattern: re.Pattern[str]) -> int: ...
def _get_base_name(dependency: str) -> str: ...
def _add_dependency(dependency: str, dependencies: list[str], processed_dependencies: set[str]) -> None: ...
def _resolve_dependencies(project_root: Path) -> tuple[str, ...]: ...
def _resolve_project_name(project_root: Path) -> str: ...
def _resolve_mamba_environments_directory() -> Path: ...
def _resolve_environment_files(project_root: Path, environment_base_name: str) -> tuple[str, Path]: ...
def _check_package_engines() -> None: ...
