from .automation import (
    ProjectEnvironment as ProjectEnvironment,
    move_stubs as move_stubs,
    delete_stubs as delete_stubs,
    verify_pypirc as verify_pypirc,
    format_message as format_message,
    colorize_message as colorize_message,
    resolve_library_root as resolve_library_root,
    generate_typed_marker as generate_typed_marker,
    resolve_project_directory as resolve_project_directory,
)

_MINIMUM_PYPI_TOKEN_LENGTH: int
_MAXIMUM_PYPI_TOKEN_LENGTH: int

def cli() -> None: ...
def process_typed_markers() -> None: ...
def process_stubs() -> None: ...
def purge_stubs() -> None: ...
def acquire_pypi_token(*, replace_token: bool) -> None: ...
def install_project(environment_name: str) -> None: ...
def uninstall_project(environment_name: str) -> None: ...
def create_environment(environment_name: str, python_version: str) -> None: ...
def remove_environment(environment_name: str) -> None: ...
def provision_environment(environment_name: str, python_version: str) -> None: ...
def import_environment(environment_name: str) -> None: ...
def export_environment(environment_name: str) -> None: ...
